config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: "home#index"
  resources :items
  resources :shops
  devise_for :users
  get "search", to: "search#search"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  mount PgHero::Engine, at: "pghero"

  # Defines the root path route ("/")
  # root "posts#index"
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  def authenticate_admin!
    redirect_to(root_path, alert: "Access denied!") unless current_user&.admin?
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def login_page?
    current_page?(new_user_session_path) || current_page?(new_user_registration_path)
  end
end

app/views/application/_footer.html.erb
  <!-- Footer -->
  <footer class="bg-gray-800 text-white py-4 mt-8">
    <div class="container mx-auto px-4">
      <div class="flex justify-between items-center">
        <div>
          <h4 class="font-bold text-lg">Company Name</h4>
          <p>&copy; 2024 Company Name. All rights reserved.</p>
        </div>
        <div>
          <a href="#" class="text-gray-400 hover:text-white mx-2">Privacy Policy</a>
          <a href="#" class="text-gray-400 hover:text-white mx-2">Terms of Service</a>
          <a href="#" class="text-gray-400 hover:text-white mx-2">Contact Us</a>
        </div>
      </div>
    </div>
  </footer>

app/views/application/_navbar.html.erb
<nav class="bg-white shadow-md p-4 sticky top-0 flex justify-between items-center">
  <a href="#"
      class="mr-4 block cursor-pointer py-1.5 font-sans text-base font-medium leading-relaxed text-inherit antialiased">
      SellMyBike.com
  </a>

  <div class="flex">
    <!-- Search Box -->
    <div class="flex items-center">
        <%= form_with url: search_path, method: :get, class: "flex items-center" do %>
            <%= heroicon "magnifying-glass", variant: :outline,  options: { class: "stroke-1 stroke-gray-600 w-5 h-5" } %>
            <input id="search-field" type="text" name="query" placeholder="Search..." class="px-2 py-2 border-transparent focus:border-transparent focus:ring-0">
        <% end %>
    </div>

    <%= link_to "New Sell", new_item_path, method: :get, class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded" %>


    <!-- User Email and Dropdown -->
    <div class="flex items-center space-x-4 px-4">
        <div class="border-r border-gray-300 h-6"></div>
        <% if user_signed_in? %>
        <div data-controller="user-dropdown">
            <div>
                <button type="button" data-action="user-dropdown#toggle click@window->dropdown#hide" 
                    class="flex text-sm font-medium text-gray-700 hover:bg-gray-50"
                <span class="text-gray-700"><%= current_user.email %></span>
                <%= heroicon "chevron-down", variant: :outline,  options: { class: "stroke-1 stroke-gray-600 w-5 h-5" } %>
                </button>
            </div>
              <div data-user-dropdown-target="menu" class="absolute border shadow shadow-xl rounded rounded-md mt-2">
                    <div  class="py-1">
                        <a href="#" data-action="user-dropdown#toggle" class="bg-gray-100 text-gray-900 block px-4 py-2 text-sm">Account settings</a>
                        <a href="#" data-action="user-dropdown#toggle" class="block text-gray-900 px-4 py-2 text-sm">Items List</a>
                        <%= link_to "Logout", destroy_user_session_path, data: { turbo_method: :delete }, class: "block text-gray-900 px-4 py-2 text-sm" %>
                    </div>
                </div>
        </div>
        <% else %>
            <%= link_to "Login", new_user_session_path, class: "text-gray-700 hover:bg-gray-50" %>
        <% end %>
    </div>
  </div>
</nav>